version: '3'
services:
  nodejs-angular-webserver-dev:
    image: cenk1cenk2/nodejs-angular-webserver-dev
    volumes:
      - ./src:/data/app
    env_file: .env
    ports:
      - ${ANGULAR_PORT:-4200}:4200
    network_mode: "bridge"
